---
ansible_user: root
ansible_password: password
prometheus_exporters:
  node_exporter:
    port: "9100"
  example_exporter0:
    port: "10000"
  example_exporter1:
    port: "10001"
  example_exporter2:
    port: "10002"
  cAdvisor:
    port: "8080"
  instrumentation-example:
    port: "12345"
  cpu-exporter:
    port: "8000"
  push_gateway:
    port: "9091"
prometheus_exporter_labels:
  systemType: 'vm'
  example: '2'