---
- name: Ensure oper group exists
  group:
    name: oper
    state: present

- name: Ensure oper user exists
  user:
    name: oper
    shell: /bin/bash
    groups: oper

- name: Ensure oper user has authorized_keys
  authorized_key:
    user: oper
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "keys/*.pub"
