---

- name: Ensure git config
  hosts: localhost
  tasks:
  - copy: 
      src: "../master.gitconfig"
      dest: "~/.gitconfig"

- name: Ensure homebrew 
  hosts: localhost
  tasks:
  - homebrew: 
      name: bat
      state: latest
  - homebrew: 
      name: jq
      state: latest